### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by miraai**
If you want them.

### CODE REVIEW

**Comment by samdivaio** [comment]
Did you fix your issue? @theoddball

**Comment by miraai** [comment]
It should be fixed

**Comment by Kwoth** [comment]
this won't work. After putty is closed it will stop since linuxaio isn't running in tmux @theoddball should know more

**Comment by theoddball** [comment]
Sam decided to not include tmux?
He said even you don't use it

**Comment by Kwoth** [comment]
I use screen. You could just replace it with screen. But it's besically the same thing. Like this it doesn't work at all :D

**Comment by theoddball** [comment]
I can add it later if you want

**Comment by samdivaio** [comment]
Why I decided to remove tmux from Installation?
- New users don't really understand how they get tmux session right after installation (even when I included that in the guide) and decide to reinstall in a different session and failing because libs are already used in a separate process.
- Running tmux right after installing is not so useful also because users prefer screen over it and they are not really going to reinstall prerequisites anytime soon.
- tmux/ screen options can actually be added to linuxAIO as an option but I believe its not gonna be any useful. 😄

**Comment by samdivaio** [comment]
@Kwoth what do you mean by "not working"?

**Comment by Kwoth** [comment]
the moment you disable putty, bot dies. It has to be running in a screen/tmux session.

**Comment by samdivaio** [comment]
😭 Read the docs [Kwoth](https://nadekobot.readthedocs.io/en/latest/guides/Linux%20Guide/#running-nadekobot) use tmux session before running the bot.

**Comment by samdivaio** [comment]
We can definitely add the tmux/screen option to linux AIO if you want 😄

**Comment by theoddball** [comment]
Just do a yes/no for tmux

**Comment by samdivaio** [comment]
With running? 🤔
I don't think curl will work that way. If it gets in tmux it will start the AIO again. So y/n won't be effective.

**Comment by samdivaio** [comment]
We need options for creating and attachin to default "nadeko" session.

**Comment by theoddball** [comment]
Maybe in aio have an option to connect to nadeko session.

Just have it attach to it

**Comment by samdivaio** [comment]
Well if you are adding tmux option, we gonna need to have create, attach and kill.
Or,
We can do this, let the command run twice, like first attach then create. Why?
First one will attach to default nadeko session, if it fails it will create the nadeko session and run the AIO.

**Comment by theoddball** [comment]
No, do option 5 or whatever.
Then do a submenu, attach or destroy. When you do run, it kills the current nadeko tmux session, then opens another one

**Comment by miraai** [comment]
Just PR changes when you decide, and I will PR to @Kwoth when its ok. Imma gonna close this.

**Comment by Kwoth** [comment]
I actually have no idea what you guys want 👍  :D

**Pull request closed without merging**
