### PR TITLE
Add nadeko service as experimental

### PR DESCRIPTION
**Pull request by MaybeGoogle**
Tested on ubuntu and arch, should work on anything that nadeko supports

### CODE REVIEW

**Comment by Kwoth** [comment]
Can someone test this?

**Comment by MaybeGoogle** [comment]
Kwoth I've literally been running my bot with this for more than a month and havent touched it since december...

Could you accept the PR? I'll add the option to the guides, emphasizing how its experimental. It also says experimental in the options for setup, too. Will also ask for people who try it to report if it worked/didnt work/other comments to me.

**Comment by Kwoth** [comment]
Thanks google but that's becoming definitely too many options, plus the guides would need to be edited. Just let Kotz see this so that if someone insists on running it as a service, they have your fork as a reference.

**Comment by MaybeGoogle** [comment]
Actually, as a replacement for pm2 (because pm2 currently doesnt work), it would result in one less option, and I would be happy to support this, including updating guides. 

Plus, linux guide needs to be updated anyways

**Pull request closed without merging**
